// App wiring: input detection, decode pipeline, events.
(function () {
  'use strict';
  const $ = (id) => document.getElementById(id);
  // Demo data is synthetic (generated by test/gen_example.py from the public BIP39 test mnemonic).
  const EXAMPLE_PSBT = 'cHNidP8BAP3jAQIAAAAHldsn6n9bvrQDGXZ68h95hn7xERXIA2IO1Q7K0POBL5UAAAAAAP3///902Pe6IPiYCNixew0FUJuO9n+Jf8+8FzcBM6fYt/sE1AEAAAAA/f///yFwPgUhhPN8aPVPAhcCWrEzzdkVoZeX1lFqEFyXgySOAgAAAAD9/////yoQaq8FRy7OnBqns1at/tKRH9BC2feS8JR+37kgda8AAAAAAP3///93jyCKLTYvURAJ0RQQiAw6Cc9SqzB12f68JswkqrgMAQEAAAAA/f///1S6VgEVb1emTlIKkisy4AJfwo7DRRsiYDTMhhgyEwbgAgAAAAD9////cxYKIhI3KhnP4CRRXMPdYf5ssiUVmi1Vu6uuzx5w8TUAAAAAAP3///8GoC5jAAAAAAAWABRz8ZdutPBQd51k6uxIQbhLUoxKMoCEHgAAAAAAFgAUzAhxtQ/bgnnlwOD0kw+6xn6/MjNOYbwAAAAAABYAFIfe0I24+BQarAeVaSjlP+1u+uUpba8dAAAAAAAWABRmmdy0ObZV8w4ge7Njtb6Yr8WVz6BoBgAAAAAAFgAUF2X3dTl9KJl0/4rx9BuTuDu0JtVAQg8AAAAAABYAFPou3foSEKv9VmXt5tPul40C4gHtAAAAAAABAR+Amy8AAAAAABYAFMDOvNbD08qMddxexi6+VTMO+RDiIQZGBLS3EP6R9YT/8IThqRWf5PhAj/84BZamBJSEdM5PoxhzxdoKVAAAgAAAAIAAAACAAAAAAAAAAAAAAQEfsHELAAAAAAAWABSckPk06lH6D2UEF3BD4JCNppKZgyEGL9Cv+lFSn5QKNY7AxQ3oEmfQv1FYymGIc0dnaUY2LFsYc8XaClQAAIAAAACAAAAAgAAAAAABAAAAAAEBHyC8vgAAAAAAFgAUDQpMWFXuaYrlKHKhRySMGJ/f98MhBn/9eLQF6m+88MvGeubYeuqQNrcrf6tZ/sReIYJiknQkGHPF2gpUAACAAAAAgAAAAIAAAAAAAgAAAAABAR+3LQMAAAAAABYAFEfoz6Hib/xGBGg0ipyyGNA0ajd4IQYgSPpuKY/KwOeG5LrMAbJ1ea7TewueDcsx4RTW+R1jkhhzxdoKVAAAgAAAAIAAAACAAAAAAAMAAAAAAQEfQEtMAAAAAAAWABTZfMAJEixqyfQFhSJJ2IkrUDfQfSEGmpSE/rdeDAMTNBcNMK4MwTPqT5FHCBpUMy4Q06vuYfsYc8XaClQAAIAAAACAAAAAgAAAAAAEAAAAAAEBH5iAHgAAAAAAFgAUmEQgSFlZ0Noj5/6QK/MVgUzHtkshBlsGU9szKsmjxSl3aX8uhmUeK8nNrDjNNjabuIrb7PCNGHPF2gpUAACAAAAAgAAAAIAAAAAABQAAAAABAR8AxAkAAAAAABYAFF5WcGsNowG3iknCdn2mBGy4/qioIQabO4OV5uBDKR9v7qCfhNpzyx4se5iBuFDDtB7GxG2R2hhzxdoKVAAAgAAAAIAAAACAAAAAAAYAAAAAAAAAIQKlMRJVWtAEDisRkWDwX8LGkaTpFn8Oe9sT+iQM2U2bKxhzxdoKVAAAgAAAAIAAAACAAQAAAAMAAAAAAAA=';
  const EXAMPLE_TX = '020000000795db27ea7f5bbeb40319767af21f79867ef11115c803620ed50ecad0f3812f950000000000fdffffff74d8f7ba20f89808d8b17b0d05509b8ef67f897fcfbc17370133a7d8b7fb04d40100000000fdffffff21703e052184f37c68f54f0217025ab133cdd915a19797d6516a105c9783248e0200000000fdffffffff2a106aaf05472ece9c1aa7b356adfed2911fd042d9f792f0947edfb92075af0000000000fdffffff778f208a2d362f511009d11410880c3a09cf52ab3075d9febc26cc24aab80c010100000000fdffffff54ba5601156f57a64e520a922b32e0025fc28ec3451b226034cc8618321306e00200000000fdffffff73160a2212372a19cfe024515cc3dd61fe6cb225159a2d55bbabaecf1e70f1350000000000fdffffff06a02e63000000000016001473f1976eb4f050779d64eaec4841b84b528c4a3280841e0000000000160014cc0871b50fdb8279e5c0e0f4930fbac67ebf32334e61bc000000000016001487ded08db8f8141aac07956928e53fed6efae5296daf1d00000000001600146699dcb439b655f30e207bb363b5be98afc595cfa0680600000000001600141765f775397d289974ff8af1f41b93b83bb426d540420f0000000000160014fa2eddfa1210abfd5665ede6d3ee978d02e201ed00000000';

  let current = null; // {model, analysis}

  // Embed mode: ?embed=1 shows only verdict + stats + money flow (see css)
  // and reports the document height to the embedding page so an iframe can
  // size itself. Only a number is posted; the parent is not otherwise touched.
  const params = new URLSearchParams(location.search);
  const embed = params.has('embed');
  if (embed) document.body.classList.add('embed');
  function postHeight() {
    if (!embed || window.parent === window) return;
    parent.postMessage({ type: 'psbt-decoder:height', height: document.documentElement.scrollHeight }, '*');
  }
  if (embed && 'ResizeObserver' in window) new ResizeObserver(postHeight).observe(document.body);

  function toBytes(text) {
    const s = text.replace(/\s+/g, '');
    if (!s) throw new Error('Paste a PSBT (base64/hex) or a raw transaction (hex).');
    if (Bytes.isHex(s)) return Bytes.hexToBytes(s);
    if (Bytes.isBase64(s)) { try { return Bytes.base64ToBytes(s); } catch (e) { throw new Error('Input looks like base64 but could not be decoded.'); } }
    throw new Error('Input is neither valid hex nor base64.');
  }

  function decodeBytes(bytes, network) {
    let model;
    if (Psbt.isPsbt(bytes)) {
      const parsed = Psbt.parsePsbt(bytes);
      model = Psbt.buildModel(parsed, 'psbt', network);
    } else {
      const segments = [];
      let tx;
      try { tx = Tx.parseTx(bytes, { segments }); }
      catch (e) { throw new Error(`Not a PSBT (no "psbt\\xff" magic) and not a valid raw transaction: ${e.message}`); }
      tx.segments = segments; tx.warnings = [];
      model = Psbt.buildModel(tx, 'rawtx', network);
      model.segments = segments; model.bytes = bytes;
    }
    return model;
  }

  function render(model) {
    const a = Analysis.analyze(model);
    current = { model, analysis: a };
    UI.renderVerdict($('verdict'), model, a);
    UI.renderStats($('stats'), model, a);
    UI.renderFlow($('flow'), model, a);
    UI.renderMoneyBar($('moneybar'), model, a);
    UI.renderChecks($('checks'), a);
    UI.renderInputs($('inputs'), model);
    UI.renderOutputs($('outputs'), model);
    UI.renderScripts($('scripts'), model);
    UI.renderHex($('hexlegend'), $('hexinfo'), $('hexview'), model);
    UI.renderPsbtFields($('psbtfields'), model);
    $('json').textContent = UI.toJSON(model, a);
    $('n-in').textContent = model.inputs.length;
    $('n-out').textContent = model.outputs.length;
    $('copyfinal').style.display = model.finalTx ? '' : 'none';
    $('results').style.display = '';
    // auto-open small lists
    if (model.inputs.length <= 3) $('inputs').querySelectorAll('.card').forEach(c => c.classList.add('open'));
    if (model.outputs.length <= 3) $('outputs').querySelectorAll('.card').forEach(c => c.classList.add('open'));
    postHeight();
  }

  function showError(msg) { const e = $('error'); e.textContent = msg; e.style.display = 'block'; $('results').style.display = 'none'; current = null; postHeight(); }
  function clearError() { $('error').style.display = 'none'; }

  let lastBytes = null;
  function decode(scroll = true) {
    clearError();
    try {
      lastBytes = toBytes($('input').value);
      render(decodeBytes(lastBytes, $('network').value));
      if (scroll) $('results').scrollIntoView({ behavior: 'smooth', block: 'start' });
    } catch (e) { console.error(e); showError('Decode failed: ' + e.message); }
  }

  $('decode').onclick = () => decode(true);
  $('input').addEventListener('keydown', (e) => { if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') decode(); });
  $('network').onchange = () => { if (lastBytes) { try { render(decodeBytes(lastBytes, $('network').value)); } catch (e) { showError(e.message); } } };
  $('clear').onclick = () => { $('input').value = ''; clearError(); $('results').style.display = 'none'; lastBytes = null; };
  $('example').onclick = () => { $('input').value = EXAMPLE_PSBT; decode(); };
  $('exampletx').onclick = () => { $('input').value = EXAMPLE_TX; decode(); };
  $('paste').onclick = async () => { try { $('input').value = await navigator.clipboard.readText(); decode(); } catch (e) { showError('Clipboard access denied — paste manually (Ctrl/Cmd+V).'); } };
  $('fileBtn').onclick = () => $('file').click();
  $('file').onchange = (e) => { if (e.target.files[0]) loadFile(e.target.files[0]); e.target.value = ''; };

  function loadFile(file) {
    const fr = new FileReader();
    fr.onload = () => {
      const bytes = new Uint8Array(fr.result);
      if (Psbt.isPsbt(bytes)) { $('input').value = Bytes.bytesToBase64(bytes); decode(); return; }
      // maybe text
      const text = new TextDecoder().decode(bytes).trim();
      if (/^[0-9a-fA-F\s]+$/.test(text) || /^[A-Za-z0-9+/=\s_-]+$/.test(text)) { $('input').value = text; decode(); }
      else { $('input').value = Bytes.bytesToHex(bytes); decode(); }
    };
    fr.readAsArrayBuffer(file);
  }
  const panel = $('input-panel');
  ['dragenter', 'dragover'].forEach(ev => panel.addEventListener(ev, (e) => { e.preventDefault(); panel.classList.add('drop-active'); }));
  ['dragleave', 'drop'].forEach(ev => panel.addEventListener(ev, (e) => { e.preventDefault(); panel.classList.remove('drop-active'); }));
  panel.addEventListener('drop', (e) => { const f = e.dataTransfer.files[0]; if (f) loadFile(f); });

  // Tabs
  $('tabs').addEventListener('click', (e) => {
    const b = e.target.closest('button'); if (!b) return;
    $('tabs').querySelectorAll('button').forEach(x => x.classList.toggle('active', x === b));
    document.querySelectorAll('.tabpane').forEach(p => p.classList.toggle('active', p.id === 'tab-' + b.dataset.tab));
  });
  // Card toggle, hex toggle, copy
  document.addEventListener('click', (e) => {
    const copy = e.target.closest('.copy');
    if (copy) { navigator.clipboard.writeText(copy.dataset.copy).then(() => { copy.textContent = 'copied'; setTimeout(() => copy.textContent = 'copy', 1200); }); e.stopPropagation(); return; }
    const th = e.target.closest('.togglehex');
    if (th) { th.closest('.scriptblock').classList.toggle('showhex'); return; }
    const head = e.target.closest('.card .head');
    if (head && !e.target.closest('a')) head.parentElement.classList.toggle('open');
  });
  $('copyjson').onclick = () => navigator.clipboard.writeText($('json').textContent);
  $('copyfinal').onclick = () => { if (current && current.model.finalTx) navigator.clipboard.writeText(current.model.finalTx.hex); };

  // Support ?psbt=... / #... in URL for convenience. ?network=<mainnet|testnet|signet|regtest>
  // selects the address encoding. Prefer the #fragment for data: it is never sent to a server.
  const netParam = params.get('network');
  if (netParam && $('network').querySelector(`option[value="${netParam}"]`)) $('network').value = netParam;
  const fromUrl = params.get('psbt') || params.get('tx') || (location.hash.length > 1 ? decodeURIComponent(location.hash.slice(1)) : '');
  if (fromUrl) {
    $('input').value = fromUrl; decode(false);
    const tab = params.get('tab');
    if (tab) { const b = $('tabs').querySelector(`button[data-tab="${tab}"]`); if (b) b.click(); }
  }
})();
